"""Added current_emissions to recommendations

Revision ID: 5adf7ad3c42a
Revises: 6476d2047ef9
Create Date: 2025-02-27 21:23:45.032231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5adf7ad3c42a'
down_revision: Union[str, None] = '6476d2047ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emission_history', 'mpg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('emission_history', 'miles',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('emission_history', 'passengers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('emission_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('recommendations', sa.Column('current_emissions', sa.Float(), nullable=False))
    op.add_column('recommendations', sa.Column('impact_value', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'impact_value')
    op.drop_column('recommendations', 'current_emissions')
    op.alter_column('emission_history', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('emission_history', 'passengers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('emission_history', 'miles',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('emission_history', 'mpg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
