"""Add more details to emission_history

Revision ID: 6476d2047ef9
Revises: c5fe4a38c125
Create Date: 2025-02-26 20:57:55.174563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6476d2047ef9'
down_revision: Union[str, None] = 'c5fe4a38c125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emission_history', sa.Column('fuel_type', sa.String(), nullable=False))
    op.add_column('emission_history', sa.Column('mpg', sa.Float(), nullable=False))
    op.add_column('emission_history', sa.Column('miles', sa.Float(), nullable=False))
    op.add_column('emission_history', sa.Column('passengers', sa.Integer(), nullable=False))
    op.alter_column('emission_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emission_history', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('emission_history', 'passengers')
    op.drop_column('emission_history', 'miles')
    op.drop_column('emission_history', 'mpg')
    op.drop_column('emission_history', 'fuel_type')
    # ### end Alembic commands ###
